services:
  my-rocm-pytorch-service:
    container_name: rocm
    image: rocm/pytorch:latest
    user: 0:0
    volumes:
      - ./ssh/:/var/lib/jenkins/.ssh/
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    shm_size: 8g
